// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231105152750_Add_Created_On_Task")]
    partial class Add_Created_On_Task
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Domain.Entities.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeWasted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2da35c41-7a77-4613-a08e-5df71b92bee6"),
                            Content = "Task 1",
                            CreatedOn = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            TimeWasted = new TimeSpan(0, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0e10cf5e-d56d-4086-b592-95f72f70dc34"),
                            Content = "Task 2",
                            CreatedOn = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            TimeWasted = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
